fps: 30
dataset_type: FreeManDataset
dataset_name: "freeman"
precomputed_folder: "./datasets/auxiliar/FreeMan/${task.task_name}/"
annotations_folder: "./datasets/annotations/FreeMan/${task.task_name}/"
dtype: float32

data_loader_valid:
    shuffle: False
    # annotations_folder: "./datasets/FreeMan"
    segments_path: "./datasets/annotations/FreeMan/${task.task_name}/segments_${task.history_sec}s-${task.prediction_horizon_sec}s_valid.csv"
    # split: "valid"
    actions: "all"
    drop_last: False


data_loader_test:
    shuffle: False
    # annotations_folder: "./datasets/FreeMan"
    segments_path: "./datasets/annotations/FreeMan/${task.task_name}/segments_${task.history_sec}s-${task.prediction_horizon_sec}s_test.csv"
    # split: "test"
    actions: "all"
    drop_last: False
