num_joints: ${eval:'int(25) if ${task.if_consider_hip} else int(17)'} #included hip even if if_consider_hip=False. For h36m 17 or 25
fps: 50
dataset_type: H36MDataset
dataset_name: "h36m"
precomputed_folder: "motpred_eval/datasets/auxiliar/Human36M/${task.task_name}/"
annotations_folder: "motpred_eval/datasets/annotations/Human36M"
dtype: float32
multimodal_threshold: 0.5

data_loader_train:
    augmentation: 0
    shuffle: True
    subjects: ["S1", "S5", "S6", "S7", "S8"]
    segments_path: "motpred_eval/datasets/annotations/Human36M/${task.task_name}/segments_${task.history_sec}s-${task.prediction_horizon_sec}s_train.csv"
    actions: "all"
    drop_last: True

data_loader_valid:
    augmentation: 0
    shuffle: False
    subjects: ["S8"]
    segments_path: "motpred_eval/datasets/annotations/Human36M/${task.task_name}/segments_${task.history_sec}s-${task.prediction_horizon_sec}s_valid.csv"
    actions: "all"
    drop_last: False


data_loader_test:
    shuffle: False
    augmentation: 0
    segments_path: "motpred_eval/datasets/annotations/Human36M/${task.task_name}/segments_${task.history_sec}s-${task.prediction_horizon_sec}s_test.csv"
    subjects: ["S9", "S11"]
    actions: "all"
    drop_last: False
    if_load_mmgt:  ${eval:'True if "probabilistic in str(${stats_mode})" else False'}
