hip_mode: vanilla
method_name: HumanMacbaseline
ckpt_path: 'checkpoints/h36m_ckpt.pt'
dataset: ${dataset.dataset_name}
seed: 0
method_batch_size: ${batch_size}
t_his: ${obs_length}
t_pred: ${pred_length}
model_mode: ${dataset_split}
num_epoch: 1001
num_data_sample: 50000
num_val_data_sample: 5000
lr: 3.e-4
padding: 'LastFrame'
Complete: True
noise_steps: 1000
ddim_timesteps: 100
scheduler: 'Cosine' # 'Cosine' 'Linear' 'Sqrt' 'Sigmoid'
num_layers: 8
num_heads: 8
latent_dims: 512
dropout: 0.2
mod_train: 0.8
mod_test: 1.0
dct_norm_enable: False
multimodal_threshold: 0.5
multimodal_th_high: 0.1
gamma: 0.9
save_model_interval: 10
save_gif_interval: 10
ema: True
vis_switch_num: 10
vis_col: 5
vis_row: 3
n_pre: 20